daily-rewards:
  day1:
    slot: 0
    amount: 1
    display-name: "&bDay 1 Reward"
    lore:
      - "&7Get started with a shiny diamond!"
    unclaimed-material: EMERALD_BLOCK
    unclaimed-display-name: "&aClick to Claim!"
    unclaimed-lore:
      - "&eYour reward is ready."
    claimed-material: REDSTONE_BLOCK
    claimed-display-name: "&cAlready Claimed"
    claimed-lore:
      "&7Next reward in: &c%hours%h %minutes%m"

  day2:
    slot: 1
    amount: 5
    display-name: "&fDay 2 Reward"
    unclaimed-material: GOLD_BLOCK
    claimed-material: REDSTONE_BLOCK
